import type { Metadata } from "next";
import { Poppins } from "next/font/google";


import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Genslug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex flex-col">
          <div className="flex items-center justify-center border-b-2  gap-2 p-4 bg-white">
            <h1 className="font-bold text-[20px]">Genslug</h1>
            <img className="w-[25px] h-[25px] mt-1" src="./icon.svg" />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
